/* all codes on this file are automatically generated by npx tsautoindex */

import { listAllTodos, ListAllTodosCondition, ListAllTodosResult } from './listAllTodos'
export { listAllTodos }

/* fixed */

export interface QueryProcessor<NAME, CONDITION, RESULT> {
  queryName: NAME
  open(condition: CONDITION): Promise<RESULT>;
  subscribe(condition: CONDITION, onNext: (value: RESULT) => void, onError?: (error: any) => void, onCompleted?: () => void): ()=>void
}

/* validate
export async function {$NAME} (): Promise<{$Name}Result>
*/
/* validate
export async function {$NAME} (condition: ${Name}Condition): Promise<{$Name}Result>
*/

/*
header:
export interface QueryProcessor {

for each exported:
  get${Name}QueryProcessor(): EventProcessor<"${Name}", ${Name}Condition), {$Name}Result>

tail:
}
*/

export interface QueryProcessorFactory {
  getListAllTodosQueryProcessor(): QueryProcessor<'ListAllTodos', ListAllTodosCondition, ListAllTodosResult>
}
