/* all codes on this file are automatically generated by npx tsautoindex */

import { TodoWasCreated, TodoWasCreatedPayload } from './todoWasCreated'
export { TodoWasCreated, TodoWasCreatedPayload }

/* fixed */
export interface EventProcessor<T> {
  process(event: T): Promise<void>;
}

/* validate
export interface ${NAME} {
  event: '${NAME}'
  at: number
  payload: ${NAME}Payload
}
*/

/*
header:
export type AllSupportedEventNames

separator: |

for each exported:
  '${NAME}'

*/
export type AllSupportedEventNames =
  'TodoWasCreated'

/*
header:
export type AllSupportedEventTypes

separator: |

for each exported:
  '${TYPE}'

*/

export type AllSupportedEventTypes =
  TodoWasCreated

/*
header:
export interface EventProcessor {

for each exported:
  get${NAME}EventProcessor(): EventProcessor<${NAME}>

tail:
}
*/

export interface EventProcessorFactory {
  getTodoWasCreatedEventProcessor(): EventProcessor<TodoWasCreated>
}
